name: BukkitPlayground
version: ${version}
main: com.zp4rker.bukkitplayground.BukkitPlayground
authors: [zp4rker]
description: ${description}
website: https://github.com/zp4rker/bukkitplayground

commands:
  copychunk:
    description: Copies the chunk the player is currently in into a new empty world
  deleteworld:
    description: Deletes the chunk_copy world
  summonentity:
    description: Teleport an entity by id to the player