name: BukkitPlayground
version: '${version}'
main: com.zp4rker.bukkitplayground.BukkitPlayground
load: STARTUP
authors: [zp4rker]
description: My testing plugin
website: https://github.com/zp4rker/bukkitplayground

commands:
  give:
    description: Gives player an item of specified amount
