name: BukkitPlayground
version: ${version}
main: com.zp4rker.bukkitplayground.BukkitPlayground
authors: [zp4rker]
description: ${description}
website: https://github.com/zp4rker/bukkitplayground
api-version: 1.13

commands:
  kill:
    description: Kills a player